### ISSUE TITLE
Not working on macOS 10.14 Beta

### ISSUE THREAD

**Issue by singuerinc** [dessibelle/Blue-Screen-Saver#4]
Should it work right? I don't think they changed anything regardless screensavers.
Thanks!

**Comment by dessibelle** [comment]
Thanks for the heads up @singuerinc! I have not had the opportunity to try. The whole screensaver architecture in my experience is a bit old and poorly documented, so I guess one can expect things to just keep working.

Could you elaborate a bit on "Not working"? Are you trying to build it on macOS 10.14 or are you just trying to run the binary linked from the README? Any interesting log output in system.log etc?

I have a vague recollection of using a deprecated (but not yet removed) mechanism for font loading, relating to `NSBundle` or `NSFont` but I'm not sure if I've taken care about that or how the API's have changed since. Essentially the code was written for OS X 10.whatever about 8 years ago. 🙂 

Feel free to troubleshoot and PR if you find anything!

**Comment by singuerinc** [comment]
Hey, Yes, I downloaded the screensaver from the readme link.
I have no idea what it's happening.

This is what I'm getting:

![screenshot 2018-06-11 at 20 17 14](https://user-images.githubusercontent.com/503676/41249524-acce7e40-6db4-11e8-93e5-13ba90fd65f0.png)

I'm not a C developer, I was trying to understand in the code to see if there was something related with the macOS version but I didn't find anything... So I need some help to know where to change the code.

Thanks!

**Comment by singuerinc** [comment]
Wait!
Actually, it works!
Is just the preview/Screen Saver Options not working, but if you select the screensaver and wait the screensaver works just fine.

**Comment by dessibelle** [comment]
Ah, good find!

The binary you downloaded is quite old, perhaps built on 10.10 or 10.11 even, so it would be interesting to know wether or not it will preview correctly if it was built on 10.14.

Ergo, if you feel like it: If you have Xcode installed it should be as simple as checking out the project and building as normal, e.g. Product → Archive, then finding the produced file and installing that manually. 

Otherwise I'll have a look at it once I've upgraded to 10.14. I highly doubt I'll do that before it's generally available though.

**Comment by dessibelle** [comment]
The preview essentially just runs the screen saver in a view rather than full screen, so I'm suspecting there could by an issue with scaling or calculating view/font sizes etc.

As mentioned earlier there has been issues with font loading previously, so I guess it's not entierly impossible System Preferences is linked against newer Frameworks than ScreenSaverEngine, preventing the latter from calling deprecated methods while ScreenSaverEngine standalone still can access them.

**Comment by singuerinc** [comment]
ok, I will try to build it and see what happen, thanks!

**Comment by singuerinc** [comment]
Hey!, I tried with the released version of Mojave and it works! So there is nothing to be fixed. Thanks!

**Comment by dessibelle** [comment]
Yeah, works for me as well on Mojave. Thanks for reporting back! Good thing I was too busy/lazy to start looking into things on Mojave beta I guess :)
