### ISSUE TITLE
“Blue Screen Saver.saver” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by binarykitchen** [dessibelle/Blue-Screen-Saver#7]
Just downloaded and installed the latest version on Catalina and then that error came up, see screenshot

<img width="417" alt="Screen Shot 2019-10-18 at 15 37 44" src="https://user-images.githubusercontent.com/177641/67061610-4decfa80-f1bd-11e9-9b8e-31260a9214e1.png">

**Comment by binarykitchen** [comment]
anyone??

**Comment by Xeiro** [comment]
Hello, I do have the same issue on Catalina.

**Comment by dessibelle** [comment]
That's because the Mac Developer Program is $99 a year, and I don't really release software professionally.

Which is why this is open source so that you can build it yourself (your computer will then will not regard itself as an untrusted developer). 

Or you can just chose to trust the binary when running it. At least with Apps, if you right click and select **Open** you'll get a different prompt which allows you to run the binary anyway. I think that would work for a screen saver too.

**Comment by binarykitchen** [comment]
Ah yeah right, trusting that worked. Many thanks for your good work. Really find this the best screensaver so far ;)

**Comment by Xeiro** [comment]
> Ah yeah right, trusting that worked. Many thanks for your good work. Really find this the best screensaver so far ;)

Hello, how did you trust it? I see no option for it. Ty
